<?php

return [
    'roles'      => [
        'guest',
        'user',
        'admin',
        'senior' => ['user', 'admin'],
    ],
    'allows'     => [
        'guest' => [
            'index' => [
                'index',
                'signin',
                'signup',
                'resetPassword',
            ],
            'help',
            // FOR MENU
            'signin',
            'signup',
//            'authomatic',
            'link',
        ],
        'user'  => [
            'index' => ['index', 'dashboard', 'home', 'signout', 'temp'],
            'user'  => ['view', 'edit'],
            'help',
//            'field',
            'dashboard',
//            'profile',
            'lead',
            'account',
//            'search',
            'patient',
            'document',
            'product',
            'activity',
            'pricebook',
//            'pricebookdetail',
            'quote',
//            'quotedetail',
            'order',
//            'orderdetail',
//            'invoice',
            'payment',
//            'mailsetting',
            'mail',
//            'setup',
//            'authomatic',
//            'note',
//            'eventlog',
//            'doctor',
            //FOR MENU
            'signout',
//            'link',
            'api',
        ],
        'admin' => [
            'index' => ['index', 'signout', 'temp'],
//            'convert',
            'help',
//            'field',
            'dashboard',
//            'profile',
            'user',
//            'mailsetting',
//            'setup',
//            'authomatic',
            // FOR MENU
            'signout',
            'api',
        ],
    ],
    'dataAccess' => [
        'user'  => [],
        'admin' => [],
    ],
];
